name: flutter_games_exchange
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  rxdart: ^0.22.0
  firebase_auth: ^0.11.1+6
  sqflite: any
  path_provider: any
  image_picker: ^0.6.1+4
  intl: ^0.15.8
  firebase_database: ^3.0.7
  url_launcher: ^5.1.2
  flutter_svg: ^0.12.4
  firebase_storage: ^3.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - images/app_icon_large.png
  - images/app_icon_124.png
  - images/vectors/active_gamepad.svg
  - images/vectors/inactive_gamepad.svg
  - images/vectors/inactive_free.svg
  - images/vectors/active_handshake.svg
  - images/vectors/active_price.svg
  - images/vectors/add_game.svg
  - images/vectors/add_wish.svg
  - images/vectors/avatar.svg
  - images/vectors/chat.svg
  - images/vectors/chat_1.svg
  - images/vectors/chat_2.svg
  - images/vectors/close.svg
  - images/vectors/close_1.svg
  - images/vectors/close_2.svg
  - images/vectors/computer.svg
  - images/vectors/computer_1.svg
  - images/vectors/email.svg
  - images/vectors/email_1.svg
  - images/vectors/facebook.svg
  - images/vectors/facebook_1.svg
  - images/vectors/filter.svg
  - images/vectors/filter_1.svg
  - images/vectors/active_free.svg
  - images/vectors/inactive_handshake.svg
  - images/vectors/inactive_price.svg
  - images/vectors/active_wish.svg
  - images/vectors/inactive_wish.svg
  - images/vectors/meeting.svg
  - images/vectors/name.svg
  - images/vectors/name_1.svg
  - images/vectors/pc.svg
  - images/vectors/placeholder.svg
  - images/vectors/ps4.svg
  - images/vectors/ps4_1.svg
  - images/vectors/sort.svg
  - images/vectors/user.svg
  - images/vectors/whatsapp.svg
  - images/vectors/xbox.svg
  - images/vectors/xbox_1.svg
  - assets/games.txt
  - assets/privacy_policy.txt
  - assets/terms_of_use.txt
  - assets/eula.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
